export const heights = ['Low', 'Medium Low', 'Medium', 'Medium High', 'High', 'Very High', 'No Height'];
export const categories = [
  'All Categories',
  'Housewares',
  'Miscellaneous',
  'Wall-mounted',
  'Wallpaper',
  'Floors',
  'Rugs',
  'Fencing',
  'Tools-Goods',
  'Ceiling Decor',
  'Interior Structures',
  'Cooking',
  'Critters',
  'Models',
];
export const sizes = [
  '0.5x0.5',
  '0.5x1',
  '1.5x1.5',
  '1x0.5',
  '1x1',
  '1x1.5',
  '1x2',
  '2x0.5',
  '2x1',
  '2x1.5',
  '2x2',
  '3x1',
  '3x2',
  '3x3',
  '4x3',
  '4x4',
  '5x5',
];
export const interactTypes = [
  'Bed',
  'Chair',
  'Kitchenware',
  'Mirror',
  'Music Player',
  'Musical Instrument',
  'Storage',
  'TV',
  'Toilet',
  'Trash',
  'Wardrobe',
  'Workbench',
  'Other',
];
export const colors_object = {
  Aqua: 'border-teal-500',
  Beige: 'border-amber-500',
  Black: 'border-slate-950',
  Blue: 'border-blue-800',
  Brown: 'border-amber-700',
  Colorful: 'border-rainbow',
  Gray: 'border-gray-500',
  Green: 'border-green-500',
  Orange: 'border-orange-300',
  Pink: 'border-rose-200',
  Purple: 'border-purple-300',
  Red: 'border-red-600',
  White: 'border-white',
  Yellow: 'border-yellow-200',
};
export const tags = [
  'Seating',
  'Table',
  'Bed',
  'Storage & Display',
  'Space Dividers',
  'Kitchen & Dining',
  'Food',
  'Drinks',
  'Lights',
  'Audiovisual',
  'Musical Instrument',
  'Appliances',
  'Bath & Hygiene',
  'Plants',
  'Business & Civic',
  'Travel & Transit',
  'Recreation & Play',
  'Outdoor & Natural',
  'Cultural & Decor',
  'Events & Franchise',
  'Door Decor',
];
export const series_list = [
  'Bunny Day',
  'Cinnamoroll',
  'Festivale',
  'Hello Kitty',
  'Kerokerokeroppi',
  'Kiki & Lala',
  'Mario',
  'Moroccan',
  'My Melody',
  'Nordic',
  'Pompompurin',
  'Turkey Day',
  'antique',
  'bamboo',
  'cardboard',
  'cherry blossoms',
  'cool',
  'cute',
  'diner',
  'dreamy',
  'elegant',
  'festive',
  'flowers',
  'frozen',
  'fruits',
  'golden',
  'imperial',
  'iron',
  'ironwood',
  'log',
  'mermaid',
  'motherly',
  'mush',
  'patchwork',
  'pirate',
  'plaza',
  'ranch',
  'rattan',
  'shell',
  'simple',
  'sloppy',
  'spooky',
  'stars',
  'throwback',
  "tree's bounty or leaves",
  'vintage',
  'wedding',
  'wooden',
  'wooden block',
];
export const sources = [
  "Nook's Cranny",
  'Crafting',
  'Nook Miles Redemption',
  'Nook Shopping Daily Selection',
  'Nook Shopping Promotion',
  'Nook Shopping Seasonal',
  'HHP Office',
  'HHP Café',
  'Cooking',
  'All villagers',
  'Birthday',
  'Blathers',
  'Brewster',
  'C.J.',
  'Cyrus',
  'Dodo Airlines',
  'Donating all art',
  'Donating all bugs',
  'Donating all fish',
  'Donating all fossils',
  'Donating all sea creatures',
  'Flick',
  'Franklin',
  'Group Stretching',
  'Gullivarrr',
  'Gulliver',
  'HHA',
  'Isabelle',
  'Jack',
  'Jingle',
  "Kapp'n",
  "Katrina's Cleansing Service",
  'Luna',
  'May Day Tour',
  'Mom',
  'Nintendo',
  'NookLink',
  'Pavé',
  'Recycle box',
  "Redd's Co-op Raffle",
  "Redd's Raffle",
  'Rover',
  'Saharah',
  "Saharah's Co-op",
  'Starting items',
  'Tom Nook',
  'Wardell',
  'Wilbur',
  'Zipper',
];
// TO ADD: DIY source "Celeste"
export const seasonals = [
  'Celeste',
  'Bunny Day',
  'Festivale',
  //'Fireworks Show',
  'Fishing Tourney',
  'Halloween',
  //'Happy Home Paradise',
  'Summer shopping',
  'Super Mario Bros.',
  'Toy Day',
  'Turkey Day',
  'Wedding Season',
  'Winter shopping',
  'acorns and pine cones',
  'cherry-blossom petals',
  'maple leaves',
  'mushrooms',
  'ornaments',
  'snowflakes',
  'summer shells',
  'young spring bamboo',
];
export const kit = {
  'Rainbow feather': 'https://acnhcdn.com/latest/MenuIcon/FeatherRainbow.png',
  Normal: 'https://acnhcdn.com/latest/MenuIcon/RemakeKit.png',
  Pumpkin: 'https://acnhcdn.com/latest/MenuIcon/SquashOrange.png',
  Bell: 'https://acnhcdn.com/latest/MenuIcon/MoneyBag010.png',
  Cyrus: 'https://acnhcdn.com/latest/NpcIcon/alp.png',
};
