export const heights = ['Low', 'Medium Low', 'Medium', 'Medium High', 'High', 'Very High', 'No Height'];
export const categories = {
  'All Categories': '全部',
  Housewares: '家具',
  Miscellaneous: '小物件',
  'Wall-mounted': '壁挂物',
  Wallpaper: '壁纸',
  Floors: '地板',
  Rugs: '地毯',
  Fencing: '栅栏',
  'Tools-Goods': '工具',
  'Ceiling Decor': '天花板',
  'Interior Structures': '内装',
  Cooking: '料理',
  Critters: '生物',
  Models: '模型',
};
export const sizes = [
  '0.5x0.5',
  '0.5x1',
  '1.5x1.5',
  '1x0.5',
  '1x1',
  '1x1.5',
  '1x2',
  '2x0.5',
  '2x1',
  '2x1.5',
  '2x2',
  '3x1',
  '3x2',
  '3x3',
  '4x3',
  '4x4',
  '5x5',
];
export const interactTypes = {
  Bed: '床',
  Chair: '座椅',
  Kitchenware: '烹饪',
  Mirror: '换外观',
  'Music Player': '唱片播放器',
  'Musical Instrument': '乐器',
  Storage: '仓库',
  TV: '电视',
  Toilet: '厕所',
  Trash: '扔垃圾',
  Wardrobe: '衣橱',
  Workbench: '工作台',
  Other: '其他',
};

export const colors_object = {
  Aqua: '蓝绿色',
  Beige: '米色',
  Black: '黑色',
  Blue: '蓝色',
  Brown: '棕色',
  Colorful: '缤纷',
  Gray: '灰色',
  Green: '绿色',
  Orange: '橙色',
  Pink: '粉红色',
  Purple: '紫色',
  Red: '红色',
  White: '白色',
  Yellow: '黄色',
};
export const tags = {
  Seating: '座椅',
  Table: '桌子',
  Bed: '床',
  'Storage & Display': '存储/展示',
  'Space Dividers': '空间/隔断',
  'Kitchen & Dining': '厨房/餐饮',
  Food: '食物',
  Drinks: '饮料',
  Lights: '灯具',
  Audiovisual: '视听',
  'Musical Instrument': '乐器',
  Appliances: '家电',
  'Bath & Hygiene': '浴室/卫生',
  Plants: '植物',
  'Business & Civic': '商业/公共',
  'Adventure & Transit': '旅行/交通',
  'Recreation & Play': '娱乐/玩耍',
  'Outdoor & Natural': '户外/自然',
  'Cultural & Decor': '文化/装饰',
  'Events & Franchise': '活动/特许',
  'Door Decor': '门饰',
};
export const series_list = {
  divider0: 'divider',
  Cinnamoroll: 'Cinnamoroll',
  'Hello Kitty': 'Hello Kitty',
  Kerokerokeroppi: 'Kerokerokeroppi',
  'Kiki & Lala': 'Kiki & Lala',
  'My Melody': 'My Melody',
  Pompompurin: 'Pompompurin',
  Mario: '马力欧',

  divider1: 'divider',
  bamboo: '竹子',
  'cherry blossoms': '樱花',
  wedding: '婚礼',
  shell: '贝壳',
  "tree's bounty or leaves": '树果/树叶',
  spooky: '鬼怪',
  mush: '蘑菇',
  frozen: '冰块',
  festive: '节日',

  divider2: 'divider',
  antique: '古董',
  cool: '酷感',
  cute: '可爱',
  dreamy: '梦幻',
  elegant: '优雅',
  imperial: '东方风',
  motherly: '妈妈',
  Moroccan: '摩洛哥',
  Nordic: '北欧',
  simple: '简单',
  throwback: '复古',
  vintage: '怀旧',

  divider3: 'divider',
  cardboard: '纸箱',
  flowers: '花朵',
  fruits: '水果',
  golden: '黄金',
  iron: '铸铁',
  ironwood: '铸铁木',
  log: '圆木',
  patchwork: '拼布',
  rattan: '藤编',
  wooden: '木制',
  'wooden block': '积木',

  divider4: 'divider',
  mermaid: '人鱼',
  pirate: '海盗',
  diner: '餐厅',
  plaza: '广场',
  ranch: '乡村',
  sloppy: '邋遢',
  stars: '星星',
};
export const sources = {
  divider0: 'divider',
  "Nook's Cranny": '商店售卖',
  Crafting: 'DIY制作',
  Cooking: '烹饪',
  'Nook Miles Redemption': '狸数兑换',
  'Nook Shopping Daily Selection': '狸端机每日购物',
  'Nook Shopping Promotion': '狸端机购物促销',
  'Nook Shopping Seasonal': '狸端机节日购物',
  'HHP Office': 'DLC快乐家办公室',
  'HHP Café': 'DLC快乐家咖啡馆',

  divider1: 'divider',
  Pavé: '阿欢',
  Zipper: '蹦蹦',
  Cyrus: '健兆',
  Jack: '南瓜王',
  Franklin: '富蓝',
  Jingle: '铃铃鹿',
  Rover: '陌陌',
  'May Day Tour': '劳动节游览',

  divider2: 'divider',
  Celeste: '傅珂',
  Gullivarrr: '海盗',
  Gulliver: '吕游',
  'C.J.': '俞司廷',
  Flick: '龙克斯',

  "Redd's Raffle": '狐利抽奖',
  "Redd's Co-op Raffle": '狐利摊位抽奖',
  Saharah: '骆岚',
  "Saharah's Co-op": '骆岚摊位',
  "Katrina's Cleansing Service": '星薇净化服务',
  Wardell: '纳提',

  divider3: 'divider',
  Blathers: '傅达',
  Brewster: '老板',
  'Tom Nook': '狸克',
  Isabelle: '西施惠',
  Luna: '梦美',
  "Kapp'n": '航平',
  Wilbur: '陆德里',

  divider4: 'divider',
  Birthday: '生日',
  Mom: '妈妈',
  'All villagers': '村民',
  'Dodo Airlines': 'Dodo 航空',
  'Group Stretching': '做操',
  HHA: '快乐家协会',
  Nintendo: '任天堂',
  NookLink: '任天堂手机App',

  divider5: 'divider',
  'Recycle box': '回收箱',
  'Starting items': '初始物品',
  'Donating all fish': '捐赠所有鱼',
  'Donating all bugs': '捐赠所有昆虫',
  'Donating all fossils': '捐赠所有化石',
  'Donating all sea creatures': '捐赠所有海洋生物',
  'Donating all art': '捐赠所有艺术品',
};

export const seasonals = {
  divider0: 'divider',
  Constellation: '星座/星星',
  'Fishing Tourney': '钓鱼大会',
  'Bug-Off': '捕虫大会',
  'Fireworks Show': '烟花大会',
  'Summer shopping': '夏季购物',
  'Winter shopping': '冬季购物',
  divider1: 'divider',
  'young spring bamboo': '竹子季',
  'cherry-blossom petals': '樱花季',
  'summer shells': '夏季贝壳季',
  'acorns and pine cones': '树果季',
  mushrooms: '蘑菇季',
  'maple leaves': '枫叶季',
  snowflakes: '雪花季',
  ornaments: '节日装饰季',
  divider2: 'divider',
  Festivale: '狂欢节',
  'Bunny Day': '复活节',
  'Wedding Season': '婚礼季',
  Halloween: '万圣节',
  'Turkey Day': '感恩节',
  'Toy Day': '圣诞节',
  // add moss?vine?
};
export const lightings = {
  Candle: '照明：蜡烛',
  Emission: '照明：发光',
  Fluorescent: '照明：荧光灯',
  Monitor: '照明：显示器',
  Shade: '照明：灯罩',
  Spotlight: '照明：聚光灯',
};
export const album_players = {
  Cheap: '便宜',
  'Hi-fi': '高保真',
  'Music Box': '音乐盒',
  Phono: '留声机',
  Retro: '复古',
};

export const kit = {
  'Rainbow feather': 'https://acnhcdn.com/latest/MenuIcon/FeatherRainbow.png',
  Normal: 'https://acnhcdn.com/latest/MenuIcon/RemakeKit.png',
  Pumpkin: 'https://acnhcdn.com/latest/MenuIcon/SquashOrange.png',
  Bell: 'https://acnhcdn.com/latest/MenuIcon/MoneyBag010.png',
  Cyrus: 'https://acnhcdn.com/latest/NpcIcon/alp.png',
};

export const translation = {
  //website display
  'Search for items...': '输入搜索...',
  'Reset All': '重置',
  Page: '页数',
  'More Filters': '更多筛选',
  'Has surface': '有台面',
  'Base variants': '有多种款式',
  'Pattern variants': '有多种图案',
  'Custom patterns': '可用设计码',
  'Sable patterns': '可用麻儿图案',
  'Function/Theme': '功能 / 主题',
  Size: '占地面积',
  Height: '高度',
  'Min Height': '高度下限',
  'Max Height': '高度上限',
  "* The player's height in the game is 15.": '* 玩家游戏中高度为15',
  Color: '颜色',
  'Interaction Type': '交互种类',
  Interaction: '交互种类',
  Category: '种类',
  Source: '来源',
  'Recipe source': '配方来源',
  Seasonal: '季节',
  Series: '系列',
  Variation: '款式',
  None: '无',
  Pattern: '图案',
  Customization: '改造信息',
  'customization kit': '改造工具组',
  'patterns only': '只能改造图案',
  bells: '铃钱',
  'Sable patterns': '可用麻儿图案',
  'Custom patterns': '可用设计码',
  'DIY Materials': 'DIY材料',
  'Lighting Type': '照明种类',
  Lighting: '照明',
  'Album Player Type': '唱片播放种类',
  'Album Player': '播放器',
  True: '有',
  False: '无',
  //categories
  'All Categories': '全部',
  Housewares: '家具',
  Miscellaneous: '小物件',
  'Wall-mounted': '壁挂物',
  Wallpaper: '壁纸',
  Floors: '地板',
  Rugs: '地毯',
  Fencing: '栅栏',
  'Tools-Goods': '工具',
  'Ceiling Decor': '天花板',
  'Interior Structures': '内装',
  Cooking: '料理',
  Critters: '生物',
  Models: '模型',
  //interactions
  Bed: '床',
  Chair: '座椅',
  Kitchenware: '烹饪',
  Mirror: '换外观',
  'Music Player': '唱片播放器',
  'Musical Instrument': '乐器',
  Storage: '仓库',
  TV: '电视',
  Toilet: '厕所',
  Trash: '扔垃圾',
  Wardrobe: '衣橱',
  Workbench: '工作台',
  Other: '其他',
  //colors
  Aqua: '蓝绿色',
  Beige: '米色',
  Black: '黑色',
  Blue: '蓝色',
  Brown: '棕色',
  Colorful: '缤纷',
  Gray: '灰色',
  Green: '绿色',
  Orange: '橙色',
  Pink: '粉红色',
  Purple: '紫色',
  Red: '红色',
  White: '白色',
  Yellow: '黄色',
  //tags
  Seating: '座椅',
  Table: '桌子',
  Bed: '床',
  'Storage & Display': '存储/展示',
  'Space Dividers': '空间/隔断',
  'Kitchen & Dining': '厨房/餐饮',
  Food: '食物',
  Drinks: '饮料',
  Lights: '灯具',
  Audiovisual: '视听',
  'Musical Instrument': '乐器',
  Appliances: '家电',
  'Bath & Hygiene': '浴室/卫生',
  Plants: '植物',
  'Business & Civic': '商业/公共',
  'Adventure & Transit': '旅行/交通',
  'Recreation & Play': '娱乐/玩耍',
  'Outdoor & Natural': '户外/自然',
  'Cultural & Decor': '文化/装饰',
  'Events & Franchise': '活动/特许',
  'Door Decor': '门饰',
  //sources
  "Nook's Cranny": '商店售卖',
  Crafting: 'DIY制作',
  Cooking: '烹饪',
  'Nook Miles Redemption': '狸数兑换',
  'Nook Shopping Daily Selection': '狸端机每日购物',
  'Nook Shopping Promotion': '狸端机购物促销',
  'Nook Shopping Seasonal': '狸端机节日购物',
  'HHP Office': 'DLC快乐家办公室',
  'HHP Café': 'DLC快乐家咖啡馆',
  Pavé: '阿欢',
  Zipper: '蹦蹦',
  Cyrus: '健兆',
  Jack: '南瓜王',
  Franklin: '富蓝',
  Jingle: '铃铃鹿',
  Rover: '陌陌',
  'May Day Tour': '劳动节游览',
  Gullivarrr: '海盗',
  Gulliver: '吕游',
  'C.J.': '俞司廷',
  Flick: '龙克斯',
  "Redd's Raffle": '狐利抽奖',
  "Redd's Co-op Raffle": '狐利摊位抽奖',
  Saharah: '骆岚',
  "Saharah's Co-op": '骆岚摊位',
  "Katrina's Cleansing Service": '星薇净化服务',
  Wardell: '纳提',
  Blathers: '傅达',
  Brewster: '老板',
  'Tom Nook': '狸克',
  Isabelle: '西施惠',
  Luna: '梦美',
  "Kapp'n": '航平',
  Wilbur: '陆德里',
  Birthday: '生日',
  Mom: '妈妈',
  'All villagers': '村民',
  'Dodo Airlines': 'Dodo 航空',
  'Group Stretching': '做操',
  HHA: '快乐家协会',
  Nintendo: '任天堂',
  NookLink: '任天堂手机App',
  'Recycle box': '回收箱',
  'Starting items': '初始物品',
  'Donating all fish': '捐赠所有鱼',
  'Donating all bugs': '捐赠所有昆虫',
  'Donating all fossils': '捐赠所有化石',
  'Donating all sea creatures': '捐赠所有海洋生物',
  'Donating all art': '捐赠所有艺术品',
  Fish: '鱼',
  Insects: '虫',
  'Sea Creatures': '海洋生物',
  //seasonals
  Celeste: '星座/星星',
  'Fishing Tourney': '钓鱼大会',
  'Bug-Off': '捕虫大会',
  'Fireworks Show': '烟花大会',
  'Summer shopping': '夏季购物',
  'Winter shopping': '冬季购物',
  'young spring bamboo': '竹子季',
  'cherry-blossom petals': '樱花季',
  'summer shells': '夏季贝壳季',
  'acorns and pine cones': '树果季',
  mushrooms: '蘑菇季',
  'maple leaves': '枫叶季',
  snowflakes: '雪花季',
  ornaments: '节日装饰季',
  Festivale: '狂欢节',
  'Bunny Day': '复活节',
  'Wedding Season': '婚礼季',
  Halloween: '万圣节',
  'Turkey Day': '感恩节',
  'Toy Day': '圣诞节',
  //lighting and album players
  Candle: '蜡烛',
  Emission: '发光',
  Fluorescent: '荧光灯',
  Monitor: '显示器',
  Shade: '灯罩',
  Spotlight: '聚光灯',
  Cheap: '便宜',
  'Hi-fi': '高保真',
  'Music Box': '音乐盒',
  Phono: '留声机',
  Retro: '复古',
  //recipe sources
  'All villagers': '所有村民',
  Balloons: '气球',
  'Basic Cooking Recipes': '基础烹饪食谱',
  'Be a Chef! DIY Recipes+': '成为厨师！DIY食谱+',
  'Big Sister villagers': '大姐姐性格村民',
  'Breaking 100 axes': '打破100把斧头',
  'Catching a barred knifejaw': '捕获条石鲷',
  'Catching a blue marlin': '捕获旗鱼',
  'Catching a dab': '捕获鲽鱼',
  'Catching a horse mackerel': '捕获竹荚鱼',
  'Catching a olive flounder': '捕获比目鱼',
  'Catching a red snapper': '捕获鲷鱼',
  'Catching a salmon': '捕获三文鱼',
  'Catching a sea bass': '捕获鲈鱼',
  'Catching a squid': '捕获鱿鱼',
  'Catching an anchovy': '捕获凤尾鱼',
  'Completing bug Critterpedia': '完成昆虫图鉴',
  'Completing fish Critterpedia': '完成鱼类图鉴',
  'Cozy Turkey Day DIY': '温馨感恩节DIY',
  'Cranky villagers': '暴躁性格村民',
  'Custom Fencing in a Flash': '快速定制围栏',
  'DIY for Beginners': '初学者DIY',
  'Daisy Mae': '曹卖',
  'Egg balloons': '彩蛋气球',
  'Egg bottles': '彩蛋瓶子',
  Fishing: '钓鱼',
  'Gold balloon': '金色气球',
  'HHP island bottles': '快乐家岛屿瓶子',
  Harvey: '巴猎',
  'Helping Gulliver 30 times': '帮助海鸥30次',
  'Jock villagers': '运动性格村民',
  "Kapp'n island bottles": '航平岛屿瓶子',
  'Lazy villagers': '悠闲性格村民',
  Leif: '然然',
  'Normal villagers': '普通性格村民',
  Pascal: '阿獭',
  'Peppy villagers': '元气性格村民',
  'Pretty Good Tools Recipes': '相当不错的工具食谱',
  'Smug villagers': '自恋性格村民',
  'Snooty villagers': '成熟性格村民',
  Snowboy: '雪哥哥',
  'Test Your DIY Skills': '测试你的DIY技能',
  'Turkey Day Recipes': '感恩节食谱',
  'Wildest Dreams DIY': '最狂野的梦想DIY',
  //series
  Cinnamoroll: 'Cinnamoroll',
  'Hello Kitty': 'Hello Kitty',
  Kerokerokeroppi: 'Kerokerokeroppi',
  'Kiki & Lala': 'Kiki & Lala',
  'My Melody': 'My Melody',
  Pompompurin: 'Pompompurin',
  Mario: '马力欧',
  bamboo: '竹子',
  'cherry blossoms': '樱花',
  wedding: '婚礼',
  shell: '贝壳',
  "tree's bounty or leaves": '树果/树叶',
  spooky: '鬼怪',
  mush: '蘑菇',
  frozen: '冰块',
  festive: '节日',
  antique: '古董',
  cool: '酷感',
  cute: '可爱',
  dreamy: '梦幻',
  elegant: '优雅',
  imperial: '东方风',
  motherly: '妈妈',
  Moroccan: '摩洛哥',
  Nordic: '北欧',
  simple: '简单',
  throwback: '复古',
  vintage: '怀旧',
  cardboard: '纸箱',
  flowers: '花朵',
  fruits: '水果',
  golden: '黄金',
  iron: '铸铁',
  ironwood: '铸铁木',
  log: '圆木',
  patchwork: '拼布',
  rattan: '藤编',
  wooden: '木制',
  'wooden block': '积木',
  mermaid: '人鱼',
  pirate: '海盗',
  diner: '餐厅',
  plaza: '广场',
  ranch: '乡村',
  sloppy: '邋遢',
  stars: '星星',
};
