export const heights = ['Low', 'Medium Low', 'Medium', 'Medium High', 'High', 'Very High', 'No Height'];
export const categories: Record<string, string> = {
  'All Categories': '全部',
  Housewares: '家具',
  Miscellaneous: '小物件',
  'Wall-mounted': '壁挂物',
  Wallpaper: '壁纸',
  Floors: '地板',
  Rugs: '地毯',
  Fencing: '栅栏',
  'Tools-Goods': '工具',
  'Ceiling Decor': '天花板',
  'Interior Structures': '内装',
  Cooking: '料理',
  Critters: '生物',
  Models: '模型',
  Equipments: '着装',
};
export const sizes = [
  '0.5x0.5',
  '0.5x1',
  '1.5x1.5',
  '1x0.5',
  '1x1',
  '1x1.5',
  '1x2',
  '2x0.5',
  '2x1',
  '2x1.5',
  '2x2',
  '3x1',
  '3x2',
  '3x3',
  '4x3',
  '4x4',
  '5x5',
];
export const interactTypes: Record<string, string> = {
  Bed: '床',
  Chair: '座椅',
  Kitchenware: '烹饪',
  Mirror: '换外观',
  'Music Player': '唱片播放器',
  'Musical Instrument': '乐器',
  Storage: '仓库',
  TV: '电视',
  Toilet: '厕所',
  Trash: '扔垃圾',
  Wardrobe: '衣橱',
  Workbench: '工作台',
  Other: '其他',
};

export const colors_object: Record<string, string> = {
  Aqua: '蓝绿色',
  Beige: '米色',
  Black: '黑色',
  Blue: '蓝色',
  Brown: '棕色',
  Colorful: '缤纷',
  Gray: '灰色',
  Green: '绿色',
  Orange: '橙色',
  Pink: '粉红色',
  Purple: '紫色',
  Red: '红色',
  White: '白色',
  Yellow: '黄色',
};
export const tags = {
  Seating: ['Chair', 'Sofa'],
  Table: ['Desk', 'Table'],
  Bed: ['Bed'],
  'Storage & Display': ['Chest', 'Dresser', 'Shelf'],
  'Space Dividers': ['Arch', 'Screen'],
  'Kitchen & Dining': ['Dining', 'Kitchen', 'Kitchen Things'],
  Food: ['DishFood'],
  Drinks: ['DishDrink'],
  Lights: ['CeilingLamp', 'Lamp'],
  Audiovisual: ['Audio', 'Game Console'],
  'Musical Instrument': ['Musical Instrument'],
  Appliances: ['Air Conditioning', 'Fan', 'Fireplace', 'Heating', 'Home Appliances', 'TV'],
  'Bath & Hygiene': ['Bathroom Things', 'Bathtub', 'Toilet'],
  Plants: ['Plants'],
  'Business & Civic': ['Facility Decor', 'Hospital', 'Museum', 'Office', 'School', 'Shop', 'Study', 'Supplies'],
  'Adventure & Transit': ['Seaside', 'Space', 'Vehicle'],
  'Recreation & Play': ['Animal', 'Playground', 'Special Fish', 'Special Insect', 'Sports', 'Toy'],
  'Outdoor & Natural': ['Garden', 'Ranch'],
  'Cultural & Decor': ['Folk Craft Decor', 'Japanese Style'],
  'Events & Franchise': [
    'Cinnamoroll',
    'Compass',
    'Easter',
    'Hello Kitty',
    'Kerokerokeroppi',
    'Kiki & Lala',
    'Mario',
    'My Melody',
    'Pompompurin',
    'Seasonal Decor',
  ],
  'Door Decor': ['House Door Decor'],
};
export const concepts: Record<string, string> = {
  divider0: 'divider',
  European: '欧式',
  ancient: '古代风',
  'city life': '城市风',
  expensive: '昂贵',
  facility: '设施',
  fancy: '花哨',
  fantasy: '幻想',
  fitness: '健身',
  'freezing cold': '寒冷',
  harmonious: '和谐',
  heritage: '遗产',
  horror: '恐怖',
  local: '野外',
  music: '音乐',
  nature: '自然',
  ocean: '海洋',
  party: '派对',
  retro: '复古',
  'sci-fi': '科幻',
  sports: '体育',
  stylish: '时尚',

  divider1: 'divider',
  'amusement park': '游乐园',
  'apparel shop': '服装店',
  arcade: '街机厅',
  bathroom: '浴室',
  café: '咖啡馆',
  "child's room": '儿童房',
  concert: '音乐会',
  'construction site': '建筑工地',
  den: '书房',
  garden: '花园',
  hospital: '医院',
  kitchen: '厨房',
  lab: '实验室',
  'living room': '客厅',
  office: '办公室',
  outdoors: '户外',
  park: '公园',
  'public bath': '公共浴室',
  resort: '度假',
  restaurant: '餐厅',
  school: '学校',
  shop: '商店',
  space: '太空',
  supermarket: '超市',
  workshop: '车间',
};
export const series_list: Record<string, string> = {
  divider0: 'divider',
  Cinnamoroll: 'Cinnamoroll',
  'Hello Kitty': 'Hello Kitty',
  Kerokerokeroppi: 'Kerokerokeroppi',
  'Kiki & Lala': 'Kiki & Lala',
  'My Melody': 'My Melody',
  Pompompurin: 'Pompompurin',
  Mario: '马力欧',

  divider1: 'divider',
  bamboo: '竹子',
  'cherry blossoms': '樱花',
  wedding: '婚礼',
  shell: '贝壳',
  "tree's bounty or leaves": '树果·落叶',
  mush: '蘑菇',
  frozen: '冰块',
  festive: '圣诞',

  divider2: 'divider',
  antique: '古董',
  cool: '酷感',
  cute: '可爱',
  dreamy: '梦幻可爱',
  elegant: '优雅',
  imperial: '东方风',
  motherly: '妈妈',
  Moroccan: '摩洛哥',
  Nordic: '北欧风',
  simple: '简约',
  throwback: '玩具',
  vintage: '怀旧',

  divider3: 'divider',
  cardboard: '纸箱',
  flowers: '花朵',
  fruits: '水果',
  golden: '黄金',
  iron: '铸铁',
  ironwood: '铸铁木',
  log: '圆木',
  patchwork: '拼布',
  rattan: '藤编',
  wooden: '木制',
  'wooden block': '积木',

  divider4: 'divider',
  mermaid: '人鱼',
  pirate: '海盗',
  diner: '餐厅',
  plaza: '广场',
  ranch: '乡村',
  sloppy: '邋遢',
  stars: '星星',
};
export const sources: Record<string, string> = {
  divider0: 'divider',
  Crafting: 'DIY制作',
  Cooking: '烹饪',
  "Nook's Cranny": '商店售卖',
  'Able Sisters': 'Able Sisters服装店',

  divider6: 'divider',
  'Nook Miles Redemption': '狸数兑换',
  'Nook Shopping Daily Selection': '狸端机每日购物',
  'Nook Shopping Promotion': '狸端机购物促销',
  'Nook Shopping Seasonal': '狸端机节日购物',
  'HHP Office': 'DLC快乐家办公室',
  'HHP Café': 'DLC快乐家咖啡馆',

  divider1: 'divider',
  Pavé: '阿欢',
  Zipper: '蹦蹦',
  Cyrus: '健兆',
  Jack: '南瓜王',
  Franklin: '富蓝',
  Jingle: '铃铃鹿',
  Rover: '陌陌',
  'May Day Tour': '劳动节游览',

  divider2: 'divider',
  Gullivarrr: '海盗',
  Gulliver: '吕游',
  'C.J.': '俞司廷',
  Flick: '龙克斯',
  Wardell: '纳提',

  divider7: 'divider',
  Saharah: '骆岚',
  "Saharah's Co-op": '骆岚摊位',
  Kicks: '薛革',
  "Kicks' Co-op": '薛革摊位',
  "Redd's Raffle": '狐利抽奖',
  "Redd's Co-op Raffle": '狐利摊位抽奖',
  "Katrina's Cleansing Service": '星薇净化服务',

  divider3: 'divider',
  Blathers: '傅达',
  Brewster: '老板',
  'Tom Nook': '狸克',
  Isabelle: '西施惠',
  Luna: '梦美',
  "Kapp'n": '航平',
  Wilbur: '陆德里',

  divider4: 'divider',
  Birthday: '生日',
  Mom: '妈妈',
  'All villagers': '村民',
  'Dodo Airlines': 'Dodo 航空',
  'Group Stretching': '做操',
  HHA: '快乐家协会',
  Nintendo: '任天堂',
  NookLink: '任天堂手机App',

  divider5: 'divider',
  'Recycle box': '回收箱',
  'Starting items': '初始物品',
  'Donating all fish': '捐赠所有鱼',
  'Donating all bugs': '捐赠所有昆虫',
  'Donating all fossils': '捐赠所有化石',
  'Donating all sea creatures': '捐赠所有海洋生物',
  'Donating all art': '捐赠所有艺术品',
};

export const seasonEvent_value: Record<string, string> = {
  "April Fools' Day": "April Fools' Day",
  Aquarius: 'Aquarius',
  Aries: 'Aries',
  'Big Game Celebration (1)': 'Big Game Celebration',
  'Big Game Celebration (2)': 'Big Game Celebration',
  Birthday: 'Birthday',
  'Bug-Off': 'Bug-Off',
  'Bunny Day': 'Bunny Day',
  'Bunny Day (ready days); Bunny Day': 'Bunny Day',
  Cancer: 'Cancer',
  Capricorn: 'Capricorn',
  'Carnival of Venice': 'Carnival of Venice',
  'Cheese Rolling': 'Cheese Rolling',
  "Children's Day": "Children's Day",
  Chuseok: 'Chuseok',
  Countdown: 'Countdown',
  'Cowboy Festival': 'Cowboy Festival',
  'Cowherd & Weaver Girl Day': 'Cowherd & Weaver Girl Day',
  'Dano Festival': 'Dano Festival',
  'Day of the Dead': 'Day of the Dead',
  'Dragon Boat Festival': 'Dragon Boat Festival',
  'Fall shopping': 'Fall shopping',
  "Father's Day": "Father's Day",
  "Father's Day (2)": "Father's Day",
  Festivale: 'Festivale',
  'Festivale (ready days); Festivale': 'Festivale',
  'Festive shopping': 'Toy Day',
  'Fireworks Show': 'Fireworks Show',
  'Fishing Tourney': 'Fishing Tourney',
  Gemini: 'Gemini',
  'Grape Harvest Festival': 'Grape Harvest Festival',
  'Groundhog Day': 'Groundhog Day',
  Halloween: 'Halloween',
  'Halloween (ready days)': 'Halloween',
  'Halloween (ready days); Halloween': 'Halloween',
  'Happy Home Paradise': 'Happy Home Paradise',
  Hinamatsuri: 'Hinamatsuri',
  "International Children's Day": "International Children's Day",
  'International Museum Day': 'International Museum Day',
  'Lantern Festival': 'Lantern Festival',
  'Le 14 juillet': 'Le 14 juillet',
  Leo: 'Leo',
  Libra: 'Libra',
  'Lunar New Year': 'Lunar New Year',
  'Marine Day': 'Marine Day',
  'May Day': 'May Day',
  'Moon-Viewing Day': 'Moon-Viewing Day',
  'Moon-Viewing Day (2)': 'Moon-Viewing Day',
  'Moon-Viewing Day (3)': 'Moon-Viewing Day',
  "Mother's Day": "Mother's Day",
  'Nanakusa Gayu': 'Nanakusa Gayu',
  'Nature Day (Nook Shopping)': 'Nature Day',
  "New Year's Day": "New Year's Day",
  "New Year's Day (Korea)": "New Year's Day",
  "New Year's Day (World)": "New Year's Day",
  "New Year's Day (Year of the Dog)": "New Year's Day",
  "New Year's Day (Year of the Dragon)": "New Year's Day",
  "New Year's Day (Year of the Horse)": "New Year's Day",
  "New Year's Day (Year of the Monkey)": "New Year's Day",
  "New Year's Day (Year of the Ox)": "New Year's Day",
  "New Year's Day (Year of the Pig)": "New Year's Day",
  "New Year's Day (Year of the Rabbit)": "New Year's Day",
  "New Year's Day (Year of the Rat)": "New Year's Day",
  "New Year's Day (Year of the Rooster)": "New Year's Day",
  "New Year's Day (Year of the Sheep)": "New Year's Day",
  "New Year's Day (Year of the Snake)": "New Year's Day",
  "New Year's Day (Year of the Tiger)": "New Year's Day",
  "New Year's Eve": "New Year's Eve",
  "New Year's Eve (Russia)": "New Year's Eve",
  Nochevieja: "New Year's Eve",
  Obon: 'Obon',
  Pisces: 'Pisces',
  'Prom (1)': 'Prom',
  'Prom (2)': 'Prom',
  'Prom (Able Sisters)': 'Prom',
  Sagittarius: 'Sagittarius',
  Scorpio: 'Scorpio',
  Setsubun: 'Setsubun',
  'Setsubun (Able Sisters)': 'Setsubun',
  'Shamrock Day': 'Shamrock Day',
  'Shamrock Day (Able Sisters)': 'Shamrock Day',
  'Shichi-Go-San': 'Shichi-Go-San',
  'Shōgatsu (1)': "New Year's Day",
  'Shōgatsu (2)': "New Year's Day",
  'Shōgatsu (3)': "New Year's Day",
  'Shōgatsu (4)': "New Year's Day",
  Silvester: "New Year's Eve",
  Singmogil: 'Singmogil',
  'Spring shopping': 'Spring shopping',
  'Summer Solstice (northern hemisphere) (2)': 'Summer Solstice',
  'Summer Solstice (northern hemisphere); Summer Solstice (southern hemisphere)': 'Summer Solstice',
  'Summer shopping': 'Summer shopping',
  'Summer shopping; Fireworks Show': 'Summer shopping; Fireworks Show',
  'Super Mario Bros.': 'Super Mario Bros.',
  Tanabata: 'Tanabata',
  Taurus: 'Taurus',
  'Tomato Festival': 'Tomato Festival',
  'Toy Day': 'Toy Day',
  'Toy Day (ready days phase 1); Toy Day (ready days phase 2); Toy Day; Toy Day (day after)': 'Toy Day',
  'Toy Day (ready days phase 2); Toy Day': 'Toy Day',
  'Toy Day (ready days phase 2); Toy Day; Toy Day (day after)': 'Toy Day',
  'Turkey Day': 'Turkey Day',
  'Turkey Day; Turkey Day (shopping days)': 'Turkey Day',
  "Valentine's Day (Nook Shopping)": "Valentine's Day",
  Virgo: 'Virgo',
  'Wedding Season': 'Wedding Season',
  'Wedding Season (Able Sisters)': 'Wedding Season Shopping',
  'Wedding Season (Nook Shopping 1)': 'Wedding Season Shopping',
  'Wedding Season (Nook Shopping 2)': 'Wedding Season Shopping',
  'Winter Solstice (northern hemisphere) (2)': 'Winter Solstice',
  'Winter Solstice (northern hemisphere) (3)': 'Winter Solstice',
  'Winter Solstice (northern hemisphere); Winter Solstice (southern hemisphere)': 'Winter Solstice',
  'Winter Solstice (southern hemisphere); Winter Solstice (northern hemisphere)': 'Winter Solstice',
  'Winter shopping': 'Winter shopping',
  'acorns and pine cones': 'acorns and pine cones',
  'cherry-blossom petals': 'cherry-blossom petals',
  'maple leaves': 'maple leaves',
  mushrooms: 'mushrooms',
  ornaments: 'ornaments',
  snowflakes: 'snowflakes',
  'summer shells': 'summer shells',
  'young spring bamboo': 'young spring bamboo',
  'π Day': 'π Day',
};

export const seasonals: Record<string, string> = {
  divider0: 'divider',
  'young spring bamboo': '02/25-05/31',
  'cherry-blossom petals': '04/01-04/10',
  'summer shells': '06/01-08/31',
  'acorns and pine cones': '09/01-12/10',
  mushrooms: '11/01-11/30',
  'maple leaves': '11/16-11/25',
  snowflakes: '12/11-02/24',
  ornaments: '12/15-01/06',
  divider1: 'divider',
  Festivale: 'Feb',
  'Bunny Day': 'Apr',
  'Wedding Season': 'Jun',
  Halloween: 'Oct',
  'Turkey Day': 'Nov',
  'Toy Day': 'Dec',
  divider2: 'divider',
  Constellation: '',
  'Fishing Tourney': '',
  'Bug-Off': '',
  'May Day': '04/29-05/07',
  'International Museum Day': '05/18-05/31',
  'Fireworks Show': 'Aug',
  'Summer shopping': '',
  'Winter shopping': '',
  Birthday: '',

  divider3: 'divider',
  "New Year's Day": '12/22-01/05',
  'Nanakusa Gayu': '01/05-01/07',
  'Big Game Celebration': '01/15-02/15',
  'Lunar New Year': '02/08-02/15',
  'Groundhog Day': '01/25-02/02',
  Setsubun: '01/25-02/03',
  'Carnival of Venice': '01/30-02/21',
  "Valentine's Day": '02/01-02/14',
  Hinamatsuri: '02/22-03/03',
  'π Day': '03/01-03/14',
  'Shamrock Day': '03/10-03/17',
  "April Fools' Day": '03/26-04/01',
  Singmogil: '04/01-04/10',
  Prom: '04/01-04/30',
  'Nature Day': '04/15-04/22',
  "Children's Day": '04/26-05/05',
  "Mother's Day": '05/01-05/31',
  'Cheese Rolling': '05/20-05/29',
  "International Children's Day": '06/01-06/15',
  "Father's Day": '06/01-06/30',
  'Wedding Season Shopping': '06/01-06/30',
  'Dragon Boat Festival': '06/13-06/22',
  'Dano Festival': '06/13-06/22',
  'Summer Solstice': '06/15-06/21',
  divider6: 'divider',
  Tanabata: '07/01-07/07',
  'Marine Day': '07/08-07/17',
  'Le 14 juillet': '07/10-07/20',
  'Cowboy Festival': '07/15-08/15',
  Obon: '08/10-08/16',
  'Cowherd & Weaver Girl Day': '08/13-08/22',
  'Tomato Festival': '08/20-08/31',
  'Grape Harvest Festival': '09/01-09/30',
  'Moon-Viewing Day': '09/20-09/29',
  Chuseok: '09/20-09/29',
  'Day of the Dead': '10/25-11/03',
  'Lantern Festival': '11/01-11/11',
  'Shichi-Go-San': '11/11-11/20',
  'Winter Solstice': '12/15-12/21',
  Countdown: '12/22-12/31',
  "New Year's Eve": '12/22-12/31',
};
export const lightings: Record<string, string> = {
  divider0: 'divider',
  Candle: '照明：蜡烛',
  Emission: '照明：发光',
  Fluorescent: '照明：荧光灯',
  Monitor: '照明：显示器',
  Shade: '照明：灯罩',
  Spotlight: '照明：聚光灯',
};
export const album_players: Record<string, string> = {
  divider0: 'divider',
  Cheap: '便宜',
  'Hi-fi': '高保真',
  'Music Box': '音乐盒',
  Phono: '留声机',
  Retro: '复古',
};
export const rugs: Record<string, string> = {
  divider0: 'divider',
  'Fruit Rugs': '水果地毯',
  'Heart Rugs': '心形地毯',
  'Icon Rugs': '图标地毯',
  'Kitchen Rugs': '厨房地毯',
  'Message Mats': '信息垫',
  'Park Rugs': '公园地毯',
  'Pattern Rugs': '图案地毯',
  'Rose Rug': '玫瑰地毯',
  'Sanrio Rugs': '三丽鸥地毯',
  'Shaggy Round Rugs': '蓬松圆地毯',
  'Simple Rugs': '简单地毯',
  'Slender Pattern Rugs': '细长图案地毯',
  'Slender Rugs': '细长地毯',
  'Wood Rugs': '木质地毯',
};

export const clothingThemes: Record<string, string> = {
  divider0: 'divider',
  comfy: '休闲',
  everyday: '日常',
  'fairy tale': '童话世界',
  formal: '正式',
  goth: '恐怖',
  outdoorsy: '户外',
  party: '派对',
  sporty: '运动',
  theatrical: '舞台',
  vacation: '度假',
  work: '工作',
};

export const clothingStyles: Record<string, string> = {
  divider0: 'divider',
  Active: '活跃',
  Cool: '酷感',
  Cute: '可爱',
  Elegant: '优雅',
  Gorgeous: '华丽',
  Simple: '简单',
};

export const clothingTypes: Record<string, string> = {
  divider0: 'divider',
  Tops: '上衣',
  Bottoms: '下装',
  'Dress-Up': '正装',
  Headwear: '头饰',
  Accessories: '配饰',
  Socks: '袜子',
  Shoes: '鞋子',
  Bags: '包',
  Umbrellas: '伞',
  'Clothing Other': '潜水服',
};

export const kit: Record<string, string> = {
  'Rainbow feather': 'https://acnhcdn.com/latest/MenuIcon/FeatherRainbow.png',
  Normal: 'https://acnhcdn.com/latest/MenuIcon/RemakeKit.png',
  Pumpkin: 'https://acnhcdn.com/latest/MenuIcon/SquashOrange.png',
  Bell: 'https://acnhcdn.com/latest/MenuIcon/MoneyBag010.png',
  Bells: 'https://acnhcdn.com/latest/MenuIcon/MoneyBag010.png',
  Poki: 'poki_icon.png',
  //Poki: 'https://dodo.ac/np/images/thumb/f/fb/Poki_NH_Inv_Icon_cropped.png/30px-Poki_NH_Inv_Icon_cropped.png',
  Cyrus: 'https://acnhcdn.com/latest/NpcIcon/alp.png',
  'Nook Miles': 'nook_icon.png',
  //'Nook Miles':
  //  'https://dodo.ac/np/images/thumb/b/b2/Nook_Miles_NH_Icon_Cropped.png/44px-Nook_Miles_NH_Icon_Cropped.png',
  'Nook Points': 'nook_point.svg',
  //'Nook Points': 'https://dodo.ac/np/images/4/4f/Nook_Points_NH_Icon.svg',
  'Heart Crystals': 'https://acnhcdn.com/latest/MenuIcon/Love.png',
};

export const translation: Record<string, string> = {
  //website display
  'No result': '无结果',
  'Search for items...': '支持中英搜索...',
  'Reset All': '重置',
  Page: '页数',
  Submit: '确定',
  'More Filters': '更多筛选',
  'Has surface': '有台面',
  'Base variants': '多种款式',
  'Pattern variants': '多种图案',
  'Custom patterns': '可用设计码',
  'Sable patterns': '可用麻儿图案',
  'Function/Theme': '功能 / 主题',
  Size: '占地',
  Height: '高度',
  'Min Height': '高度下限',
  'Max Height': '高度上限',
  Min: '下限',
  Max: '上限',
  "Player's height in the game is 15.": '玩家游戏中高度为15',
  Color: '颜色',
  'Interaction Type': '交互种类',
  Keyword: '关键词',
  Interaction: '交互种类',
  Category: '种类',
  Source: '来源',
  'Recipe source': '配方来源',
  Seasonal: '季节',
  'Furniture Series': '家具系列',
  Series: '系列',
  Variation: '款式',
  None: '无',
  Pattern: '图案',
  Customization: '改造信息',
  'Season Event': '季节',
  'customization kit': '改造工具组',
  'patterns only': '只能改造图案',
  Price: '价格',
  bells: '铃钱',
  Bells: '铃钱',
  Poki: 'Poki',
  'Heart Crystals': '爱的结晶',
  'DIY Materials': 'DIY材料',
  'Lighting Type': '照明种类',
  Lighting: '照明',
  'Album Player Type': '唱片播放种类',
  'Album Player': '播放器',
  'Rug Filter': '地毯种类',
  Rug: '地毯',
  'Other Filters': '其它选项',
  'Furniture Concept': '家具概念',
  Concept: '概念',
  True: '是',
  False: '否',
  '99,000 Bells': '99,000 铃钱',
  '50,000 Bells': '50,000 铃钱',
  "More details on the item's": '更多信息请访问本物品的',
  'Nookipedia Page': 'Nookipedia 页面',
  Pumpkin: '南瓜',
  'Rainbow feather': '彩虹羽毛',
  '30 turnips': '30颗大头菜',
  '10 turnips': '10颗大头菜',
  Niko: '尼可',
  'Exclude clothing': '排除所有着装',
  'Nook Miles': '狸数',
  'Nook Points': '狸端机入口站点数',
  //categories
  'All Categories': '全部',
  Housewares: '家具',
  Miscellaneous: '小物件',
  'Wall-mounted': '壁挂物',
  Wallpaper: '壁纸',
  Floors: '地板',
  Rugs: '地毯',
  Fencing: '栅栏',
  'Tools-Goods': '工具',
  'Ceiling Decor': '天花板',
  'Interior Structures': '内装',
  Cooking: '料理',
  Critters: '生物',
  Models: '模型',
  Equipments: '着装',
  Feb: '二月',
  Apr: '四月',
  Jun: '六月',
  Aug: '八月',
  Oct: '十月',
  Nov: '十一月',
  Dec: '十二月',
  //interactions
  Bed: '床',
  Chair: '座椅',
  Kitchenware: '烹饪',
  Mirror: '换外观',
  'Music Player': '唱片播放器',
  'Musical Instrument': '乐器',
  Storage: '仓库',
  TV: '电视',
  Toilet: '厕所',
  Trash: '扔垃圾',
  Wardrobe: '衣橱',
  Workbench: '工作台',
  Other: '其他',
  //colors
  Aqua: '蓝绿色',
  Beige: '米色',
  Black: '黑色',
  Blue: '蓝色',
  Brown: '棕色',
  Colorful: '缤纷',
  Gray: '灰色',
  Green: '绿色',
  Orange: '橙色',
  Pink: '粉红色',
  Purple: '紫色',
  Red: '红色',
  White: '白色',
  Yellow: '黄色',
  //tags
  Seating: '座椅',
  Table: '桌子',
  'Storage & Display': '存储/展示',
  'Space Dividers': '空间/隔断',
  'Kitchen & Dining': '厨房/餐饮',
  Food: '食物',
  Drinks: '饮料',
  Lights: '灯具',
  Audiovisual: '视听',
  Appliances: '家电',
  'Bath & Hygiene': '浴室/卫生',
  Plants: '植物',
  'Business & Civic': '商业/公共',
  'Adventure & Transit': '旅行/交通',
  'Recreation & Play': '娱乐/玩耍',
  'Outdoor & Natural': '户外/自然',
  'Cultural & Decor': '文化/装饰',
  'Events & Franchise': '活动/特许',
  'Door Decor': '门饰',
  //sources
  "Nook's Cranny": 'Nook商店售卖',
  'Able Sisters': 'Able Sisters售卖',
  Crafting: 'DIY制作',
  'Nook Miles Redemption': '狸数兑换',
  'Nook Shopping Daily Selection': '狸端机每日购物',
  'Nook Shopping Promotion': '狸端机购物促销',
  'Nook Shopping Seasonal': '狸端机节日购物',
  'HHP Office': 'DLC快乐家办公室',
  'HHP Café': 'DLC快乐家咖啡馆',
  Pavé: '阿欢',
  Zipper: '蹦蹦',
  Cyrus: '健兆',
  Jack: '南瓜王',
  Franklin: '富蓝',
  Jingle: '铃铃鹿',
  Rover: '陌陌',
  'May Day Tour': '劳动节游览',
  Gullivarrr: '海盗',
  Gulliver: '吕游',
  'C.J.': '俞司廷',
  Flick: '龙克斯',
  "Redd's Raffle": '狐利抽奖',
  "Redd's Co-op Raffle": '狐利摊位抽奖',
  Saharah: '骆岚',
  "Saharah's Co-op": '骆岚摊位',
  Kicks: '薛革',
  "Kicks' Co-op": '薛革摊位',
  "Katrina's Cleansing Service": '星薇净化服务',
  Wardell: '纳提',
  Blathers: '傅达',
  Brewster: '老板',
  'Tom Nook': '狸克',
  Isabelle: '西施惠',
  Luna: '梦美',
  "Kapp'n": '航平',
  Wilbur: '陆德里',
  Birthday: '生日',
  Mom: '妈妈',
  'All villagers': '村民',
  'Dodo Airlines': 'Dodo 航空',
  'Group Stretching': '做操',
  HHA: '快乐家协会',
  Nintendo: '任天堂',
  NookLink: '任天堂手机App',
  'Recycle box': '回收箱',
  'Starting items': '初始物品',
  'Donating all fish': '捐赠所有鱼',
  'Donating all bugs': '捐赠所有昆虫',
  'Donating all fossils': '捐赠所有化石',
  'Donating all sea creatures': '捐赠所有海洋生物',
  'Donating all art': '捐赠所有艺术品',
  Fish: '鱼',
  Insects: '虫',
  'Sea Creatures': '海洋生物',
  //seasonals
  Celeste: '傅珂',
  Constellation: '星座/星星',
  'Fishing Tourney': '钓鱼大会',
  'Bug-Off': '捕虫大会',
  'Fireworks Show': '烟火大会',
  'Summer shopping': '夏季购物',
  'Winter shopping': '冬季购物',
  'young spring bamboo': '春笋季',
  'cherry-blossom petals': '樱花季',
  'summer shells': '夏季贝壳季',
  'acorns and pine cones': '松果和橡栗季',
  mushrooms: '蘑菇季',
  'maple leaves': '枫叶季',
  snowflakes: '雪花季',
  ornaments: '节日装饰季',
  Festivale: '狂欢节',
  'Bunny Day': '复活节',
  'Wedding Season': '结婚季节',
  Halloween: '万圣节',
  'Turkey Day': '感恩节',
  'Toy Day': '平安夜',
  //lighting and album players
  Candle: '蜡烛',
  Emission: '发光',
  Fluorescent: '荧光灯',
  Monitor: '显示器',
  Shade: '灯罩',
  Spotlight: '聚光灯',
  Cheap: '便宜',
  'Hi-fi': '高保真',
  'Music Box': '音乐盒',
  Phono: '留声机',
  Retro: '复古',
  //recipe sources
  Balloons: '气球',
  'Basic Cooking Recipes': '方便快捷！料理手册',
  'Be a Chef! DIY Recipes+': '料理也能DIY！方程式＋',
  'Big Sister villagers': '大姐姐性格村民',
  'Breaking 100 axes': '打破100把斧头',
  'Catching a barred knifejaw': '捕获条石鲷',
  'Catching a blue marlin': '捕获旗鱼',
  'Catching a dab': '捕获鲽鱼',
  'Catching a horse mackerel': '捕获竹荚鱼',
  'Catching a olive flounder': '捕获比目鱼',
  'Catching a red snapper': '捕获鲷鱼',
  'Catching a salmon': '捕获三文鱼',
  'Catching a sea bass': '捕获鲈鱼',
  'Catching a squid': '捕获鱿鱼',
  'Collecting earth eggs': '收集地面蛋',
  'Collecting leaf eggs': '收集叶子蛋',
  'Collecting sky eggs': '收集飞天蛋',
  'Collecting stone eggs': '收集岩石蛋',
  'Collecting water eggs': '收集鱼儿蛋',
  'Learning all egg outfit DIYs': '学习所有蛋系列服装DIY',
  'Collecting wood eggs': '收集森林蛋',
  'Catching an anchovy': '捕获凤尾鱼',
  'Completing bug Critterpedia': '完成昆虫图鉴',
  'Completing fish Critterpedia': '完成鱼类图鉴',
  'Cozy Turkey Day DIY': '多彩多姿感恩节DIY',
  'Cranky villagers': '暴躁性格村民',
  'Custom Fencing in a Flash': '轻轻松松！爽快改造书',
  'DIY for Beginners': '新手DIY手册',
  'Daisy Mae': '曹卖',
  'Egg balloons': '彩蛋气球',
  'Egg bottles': '彩蛋瓶子',
  Fishing: '钓鱼',
  'Gold balloon': '金色气球',
  'HHP island bottles': '快乐家岛屿瓶子',
  Harvey: '巴猎',
  'Helping Gulliver 30 times': '帮助吕游30次',
  'Jock villagers': '运动性格村民',
  "Kapp'n island bottles": '航平岛屿瓶子',
  'Lazy villagers': '悠闲性格村民',
  Leif: '然然',
  'Normal villagers': '普通性格村民',
  Pascal: '阿獭',
  'Peppy villagers': '元气性格村民',
  'Pretty Good Tools Recipes': '平常就能用！道具手册',
  'Smug villagers': '自恋性格村民',
  'Snooty villagers': '成熟性格村民',
  Snowboy: '雪哥哥',
  'Test Your DIY Skills': '挑战！DIY手册',
  'Turkey Day Recipes': '感恩节·料理',
  'Wildest Dreams DIY': '竟然能这样？！DIY',
  'Hitting a rock': '捡起击打石头掉出的金矿石',
  //series
  Cinnamoroll: 'Cinnamoroll',
  'Hello Kitty': 'Hello Kitty',
  Kerokerokeroppi: 'Kerokerokeroppi',
  'Kiki & Lala': 'Kiki & Lala',
  'My Melody': 'My Melody',
  Pompompurin: 'Pompompurin',
  Mario: '马力欧',
  bamboo: '竹子',
  'cherry blossoms': '樱花',
  wedding: '婚礼',
  shell: '贝壳',
  "tree's bounty or leaves": '树果·落叶',
  spooky: '鬼怪',
  mush: '蘑菇',
  frozen: '冰块',
  festive: '圣诞',
  antique: '古董',
  cool: '酷感',
  cute: '可爱',
  dreamy: '梦幻可爱',
  elegant: '优雅',
  imperial: '东方风',
  motherly: '妈妈',
  Moroccan: '摩洛哥',
  Nordic: '北欧',
  simple: '简约',
  throwback: '玩具',
  vintage: '怀旧',
  cardboard: '纸箱',
  flowers: '花朵',
  fruits: '水果',
  golden: '黄金',
  iron: '铸铁',
  ironwood: '铸铁木',
  log: '圆木',
  patchwork: '拼布',
  rattan: '藤编',
  wooden: '木制',
  'wooden block': '积木',
  mermaid: '人鱼',
  pirate: '海盗',
  diner: '餐厅',
  plaza: '广场',
  ranch: '乡村',
  sloppy: '邋遢',
  stars: '星星',
  //concepts
  divider0: 'divider',
  European: '欧式',
  ancient: '古代风',
  'city life': '城市风',
  expensive: '昂贵',
  facility: '设施',
  fancy: '花哨',
  fantasy: '幻想',
  fitness: '健身',
  'freezing cold': '寒冷',
  harmonious: '和谐',
  heritage: '遗产',
  horror: '恐怖',
  local: '野外',
  music: '音乐',
  nature: '自然',
  ocean: '海洋',
  party: '派对',
  retro: '复古',
  'sci-fi': '科幻',
  sports: '体育',
  stylish: '时尚',

  divider1: 'divider',
  'amusement park': '游乐园',
  'apparel shop': '服装店',
  arcade: '街机厅',
  bathroom: '浴室',
  café: '咖啡馆',
  "child's room": '儿童房',
  concert: '音乐会',
  'construction site': '建筑工地',
  den: '书房',
  garden: '花园',
  hospital: '医院',
  kitchen: '厨房',
  lab: '实验室',
  'living room': '客厅',
  office: '办公室',
  outdoors: '户外',
  park: '公园',
  'public bath': '公共浴室',
  resort: '度假',
  restaurant: '餐厅',
  school: '学校',
  shop: '商店',
  space: '太空',
  supermarket: '超市',
  workshop: '车间',
  //rugs
  'Fruit Rugs': '水果地毯',
  'Heart Rugs': '心形地毯',
  'Icon Rugs': '图标地毯',
  'Kitchen Rugs': '厨房地毯',
  'Message Mats': '信息垫',
  'Park Rugs': '公园地毯',
  'Pattern Rugs': '图案地毯',
  'Rose Rug': '玫瑰地毯',
  'Sanrio Rugs': '三丽鸥地毯',
  'Shaggy Round Rugs': '蓬松圆地毯',
  'Simple Rugs': '简单地毯',
  'Slender Pattern Rugs': '细长图案地毯',
  'Slender Rugs': '细长地毯',
  'Wood Rugs': '木质地毯',
  //Clothing
  'Equipment Filters': '着装选项',
  'Clothing Theme': '着装主题',
  'Clothing Style': '着装风格',
  'Clothing Type': '着装种类',
  'Clothing Themes': '着装主题',
  'Clothing Styles': '着装风格',
  'Clothing Types': '着装种类',
  Themes: '主题',
  Theme: '主题',
  Styles: '风格',
  Style: '风格',
  'Villager Equippable': '小动物是否可以穿戴',
  //Themes
  comfy: '舒适',
  everyday: '日常',
  'fairy tale': '童话故事',
  formal: '正式',
  goth: '哥特风',
  outdoorsy: '户外风',
  sporty: '运动',
  theatrical: '戏剧性',
  vacation: '度假',
  work: '工作',
  //Styles
  Active: '活跃',
  Cool: '酷感',
  Cute: '可爱',
  Elegant: '优雅',
  Gorgeous: '华丽',
  Simple: '简单',
  //Types
  Accessories: '配饰',
  Tops: '上衣',
  Shoes: '鞋子',
  Bottoms: '下装',
  Socks: '袜子',
  Umbrellas: '伞',
  Bags: '包',
  'Clothing Other': '潜水服',
  'Dress-Up': '正装',
  Headwear: '头饰',
  //More season events
  "April Fools' Day": '愚人节',
  Aquarius: '水瓶座',
  Aries: '白羊座',
  'Big Game Celebration': '大比赛',
  Cancer: '巨蟹座',
  Capricorn: '摩羯座',
  'Cheese Rolling': '滚奶酪节',
  "Children's Day": '儿童节',
  Chuseok: '秋夕',
  Countdown: '跨年倒计时',
  'Cowboy Festival': '牛仔节',
  'Cowherd & Weaver Girl Day': '七夕',
  'Dano Festival': '端午节(韩国)',
  'Day of the Dead': '亡灵节',
  'Dragon Boat Festival': '端午节',
  "Father's Day": '父亲节',
  'Festive shopping': '节日购物',
  Gemini: '双子座',
  'Grape Harvest Festival': '葡萄丰收节',
  'Groundhog Day': '土拨鼠日',
  'Happy Home Paradise': '快乐家乐园',
  Hinamatsuri: '女儿节',
  "International Children's Day": '国际儿童节',
  'International Museum Day': '国际博物馆日',
  Leo: '狮子座',
  Libra: '天秤座',
  'Lunar New Year': '农历新年',
  'Marine Day': '海之日',
  'May Day': '劳动节',
  'Moon-Viewing Day': '中秋节',
  "Mother's Day": '母亲节',
  'Nanakusa Gayu': '七草粥',
  'Nature Day': '地球日',
  "New Year's Day": '元旦',
  "New Year's Day (Korea)": '元旦（韩国）',
  "New Year's Day (World)": '元旦（世界）',
  "New Year's Day (Year of the Dog)": '元旦（狗年）',
  "New Year's Day (Year of the Dragon)": '元旦（龙年）',
  "New Year's Day (Year of the Horse)": '元旦（马年）',
  "New Year's Day (Year of the Monkey)": '元旦（猴年）',
  "New Year's Day (Year of the Ox)": '元旦（牛年）',
  "New Year's Day (Year of the Pig)": '元旦（猪年）',
  "New Year's Day (Year of the Rabbit)": '元旦（兔年）',
  "New Year's Day (Year of the Rat)": '元旦（鼠年）',
  "New Year's Day (Year of the Rooster)": '元旦（鸡年）',
  "New Year's Day (Year of the Sheep)": '元旦（羊年）',
  "New Year's Day (Year of the Snake)": '元旦（蛇年）',
  "New Year's Day (Year of the Tiger)": '元旦（虎年）',
  "New Year's Eve": '跨年夜',
  Nochevieja: '跨年夜',
  Obon: '盂兰盆节',
  Pisces: '双鱼座',
  Prom: '毕业舞会',
  Sagittarius: '射手座',
  Scorpio: '天蝎座',
  Setsubun: '节分',
  'Setsubun (Able Sisters)': '节分（Able姐妹）',
  'Shamrock Day': '三叶草日',
  'Shamrock Day (Able Sisters)': '三叶草日（Able姐妹）',
  'Shichi-Go-San': '七五三节',
  Shōgatsu: '日本正月',
  Silvester: '跨年夜',
  Singmogil: '植树节',
  'Summer Solstice': '夏至',
  'Super Mario Bros.': '超级马里奥兄弟',
  Tanabata: '日本七夕',
  Taurus: '金牛座',
  'Tomato Festival': '西红柿节',
  Virgo: '处女座',
  'Wedding Season Shopping': '六月新娘购物',
  'Winter Solstice': '冬至',
  'π Day': '圆周率日',
  'Carnival of Venice': '威尼斯狂欢节',
  'Fall shopping': '秋季购物',
  'Le 14 juillet': '巴士底日',
  'Lantern Festival': '圣马丁节',
  'Prom (Able Sisters)': '毕业舞会（Able姐妹）',
  'Spring shopping': '春季购物',
  'Summer shopping; Fireworks Show': '夏季购物; 烟火大会',
  "Valentine's Day": '情人节',
};
